version: "3.3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile-dev
        image: api:dev
        environment:
            MYSQL_HOST: db
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test
            REDIS_HOST: redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
        working_dir: /app
        stdin_open: true
        tty: true
        entrypoint: bash
    db:
        image: mysql:5
        environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: test
    redis:
        image: redis:alpine
